plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openapi.generator' version '7.14.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-restclient'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'io.swagger.core.v3:swagger-annotations-jakarta:2.2.30'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

}

def generatedOpenApiDir = layout.buildDirectory.dir('generated/openapi')

openApiGenerate {
    generatorName = 'spring'
    skipValidateSpec = true
    inputSpec = "$rootDir/apispec/openapi.yaml"
    outputDir = generatedOpenApiDir.get().asFile.absolutePath
    modelPackage = 'com.example.parkingmanager.adapter.out.parkingapi.generated.model'
    apiPackage = 'com.example.parkingmanager.adapter.out.parkingapi.generated.api'
    invokerPackage = 'com.example.parkingmanager.adapter.out.parkingapi.generated'
    globalProperties = [
        apis             : 'false',
        models           : '',
        supportingFiles  : 'false',
        modelDocs        : 'false',
        modelTests       : 'false'
    ]
    configOptions = [
        dateLibrary            : 'java8',
        useSpringBoot3          : 'true',
        openApiNullable        : 'false',
        hideGenerationTimestamp: 'true'
    ]
}

sourceSets {
    main {
        java {
            srcDir generatedOpenApiDir.map { it.dir('src/main/java') }
        }
    }
}

tasks.named('compileJava') {
    dependsOn tasks.named('openApiGenerate')
}

tasks.named('test') {
    useJUnitPlatform()
}
